CREATE TABLE public.produtos (
    id int4 DEFAULT main.incid('public'::character varying, 'produtos'::character varying) NOT NULL,
    nome varchar (255) NOT NULL,
    unidades_id int4 NOT NULL,
    codigobarra bpchar(13) NULL,
    fabricantes_id int4 NULL,
    estoque_atual numeric(10, 4) DEFAULT 0 NULL,
    ncm varchar(20) NULL,
    qtd_embalagem int4 NOT NULL,
    registro_ms bpchar(13) NULL,
    grupos_terapeuticos_id int4 NOT NULL,
    produto_referencia varchar(255) NULL,
    dcb_id int4 NOT NULL,
    vl_fabrica numeric(10, 2) DEFAULT 0 NULL,
    vl_custo numeric(10, 2) DEFAULT 0 NULL,
    vl_venda numeric(10, 3) DEFAULT 0 NULL,
    vl_ult_comp numeric(10, 2) DEFAULT 0 NULL,
    vl_ult_ven numeric(10, 3) DEFAULT 0 NULL,
    dt_ult_comp date NULL,
    dt_ult_ven date NULL,
    dt_atualizacao date NULL,
    dt_cadastro date DEFAULT CURRENT_DATE NULL,
    tt_entrada int4 DEFAULT 0 NULL,
    tt_saida int4 DEFAULT 0 NULL,
    tt_descarte int4 DEFAULT 0 NULL,
    ativo bool DEFAULT true NULL,
    CONSTRAINT produtos_pkey PRIMARY KEY (id),
    CONSTRAINT fk_dcb FOREIGN KEY (dcb_id) REFERENCES public.dcb(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_fabricante FOREIGN KEY (fabricantes_id) REFERENCES public.fabricantes(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_grupo_terapeutico FOREIGN KEY (grupos_terapeuticos_id) REFERENCES public.grupos_terapeuticos(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_unidade FOREIGN KEY (unidades_id) REFERENCES public.unidades(id) ON DELETE SET NULL ON UPDATE CASCADE
);